esphome:
  name: esphome-web-209bc6
  friendly_name: IVT490

esp8266:
  board: d1_mini

external_components:
  - source:
      type: local
      path: components
    components: [ivt495twin, custom_digipot]

# Enable Home Assistant API
api:
  encryption:
    key: "648n6wFHtyv+pvCgiPdyk7xlHXnYRZUycyEdB411G8A="
  services:
    - service: control_pot
      variables:
        level: float
      then:
        - number.set:
            id: digipot_level
            value: !lambda "return level * 100;"

number:
  - platform: template
    name: "Temp level"
    id: digipot_level
    optimistic: true
    min_value: 0
    max_value: 100
    initial_value: 0
    restore_value: true
    step: 1
    mode: slider
    on_value:
      then:
        - output.set_level:
            id: boiler_digipot
            level: !lambda "return x / 100.0;"

ota:
  platform: esphome

# UART settings for IVT RX connection
uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  rx_buffer_size: 512
  baud_rate: 9600

# SPI Connection to the resistor device
spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

output:
  - platform: custom_digipot
    id: boiler_digipot
    cs_pin: 16

button:
  - platform: template
    name: Temp PLUS
    id: digipot_plus
    on_press:
      - logger.log: Button PLUS Pressed
      - number.set:
          id: digipot_level
          value: !lambda "return id(digipot_level).state+1;"

  - platform: template
    name: Temp MINUS
    id: digipot_minus
    on_press:
      - logger.log: Button MINUS Pressed
      - number.set:
          id: digipot_level
          value: !lambda "return id(digipot_level).state-1;"

  - platform: template
    name: Temp SETLOW
    id: digipot_setlow
    on_press:
      - logger.log: Button LOW Pressed
      - number.set:
          id: digipot_level
          value: !lambda "return 30;"

  - platform: template
    name: Temp SETHIGH
    id: digipot_sethigh
    on_press:
      - logger.log: Button HIGH Pressed
      - number.set:
          id: digipot_level
          value: !lambda "return 70;"

switch:
  - platform: gpio
    pin: GPIO02
    id: led_switch
    name: "Led Switch"
    icon: "mdi:gate"

  - platform: gpio
    pin: GPIO0
    id: ext_int
    name: "ext_int"
    icon: "mdi:gate"

sensor:
  - name: "ivt Framlednings temp"
    platform: template
    id: ivtFramledning
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt Ute temp"
    platform: template
    id: ivtUte
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt Tappvarmvatten Topp temp"
    platform: template
    id: ivtTappvarmvattenTopp
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt Varmvatten Mitt temp"
    platform: template
    id: ivtVarmvattenMitt
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt Varmevatten Botten temp"
    platform: template
    id: ivtVarmevattenBotten
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt Rums temp"
    platform: template
    id: ivtRumstemp
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivtHetgas  temp"
    platform: template
    id: ivtHetgas
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt Extra Acc-Tank temp"
    platform: template
    id: ivtExtraAccTank
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt Tryckvakt"
    platform: template
    id: ivtTryckvakt
    lambda: "return {};"

  - name: "ivt Högtryck"
    platform: template
    id: ivtHogtryck
    lambda: "return {};"

  - name: "ivt Lågtryck"
    platform: template
    id: ivtLogtryck
    lambda: "return {};"

  - name: "ivt Semester aktiv"
    platform: template
    id: ivtSemesteraktiv
    lambda: "return {};"

  - name: "ivt Kompressor aktiv"
    platform: template
    id: ivtKompressoraktiv
    lambda: "return {};"

  - name: "ivt SV1 Öppna"
    platform: template
    id: ivtSV1Oppna
    lambda: "return {};"

  - name: "ivt SV1 Stäng"
    platform: template
    id: ivtSV1Stang
    lambda: "return {};"

  - name: "ivt P1 Rad"
    platform: template
    id: ivtP1Rad
    lambda: "return {};"

  - name: "ivt Fläkt"
    platform: template
    id: ivtFlakt
    lambda: "return {};"

  - name: "ivt Larm aktiv"
    platform: template
    id: ivtLarmaktiv
    lambda: "return {};"

  - name: "ivt Extern P2 "
    platform: template
    id: ivtExternP2
    lambda: "return {};"

  - name: "ivt LLT GT1 temp"
    platform: template
    id: ivtLLTGT1
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt LL GT1 temp"
    platform: template
    id: ivtLLGT1
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt BV GT1 temp"
    platform: template
    id: ivtBVGT1
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt UL GT1 temp"
    platform: template
    id: ivtULGT1
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt UL GT3:2 temp"
    platform: template
    id: ivtULGT3_2
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt LL GT3:3 temp"
    platform: template
    id: ivtLLGT3_3
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt BV GT3:3 temp"
    platform: template
    id: ivtBVGT3_3
    unit_of_measurement: "°C"
    lambda: "return {};"

  - name: "ivt SV3 BV Förskj"
    platform: template
    id: ivtSV3BVForskj
    lambda: "return {};"

  - name: "ivt Effekt ink vit VV behov"
    platform: template
    id: ivtEffektinkvitVVbehov
    lambda: "return {};"

  - name: "ivt  Tillskotstimer VV behov"
    platform: template
    id: ivtTillskotstimerVVbehov
    lambda: "return {};"

  - name: "ivt  Tappv prio"
    platform: template
    id: ivtTappvprio
    lambda: "return {};"

  - name: "ivt Tillskott i 10"
    platform: template
    id: ivtTillskotti10
    lambda: "return {};"

  - name: "ivt Tillskott RAD"
    platform: template
    id: ivtTillskottRAD
    lambda: "return {};"

  - name: "ivt Tillskott Tillägg"
    platform: template
    id: ivtTillskottTillagg
    lambda: "return {};"

  - name: "ivt Default SV2 Open"
    platform: template
    id: ivtDefaultSV2Open
    lambda: "return {};"

# IVT reader component
ivt495twin:
  id: ivt_reader
  uart_id: uart_bus
  sensor1: ivtFramledning
  sensor2: ivtUte
  sensor3: ivtTappvarmvattenTopp
  sensor4: ivtVarmvattenMitt
  sensor5: ivtVarmevattenBotten
  sensor6: ivtRumstemp
  sensor7: ivtHetgas
  sensor8: ivtExtraAccTank
  sensor9: ivtTryckvakt
  sensor10: ivtHogtryck
  sensor11: ivtLogtryck
  sensor12: ivtSemesteraktiv
  sensor13: ivtKompressoraktiv
  sensor14: ivtSV1Oppna
  sensor15: ivtSV1Stang
  sensor16: ivtP1Rad
  sensor17: ivtFlakt
  sensor18: ivtLarmaktiv
  sensor19: ivtExternP2
  sensor20: ivtLLTGT1
  sensor21: ivtLLGT1
  sensor22: ivtBVGT1
  sensor23: ivtULGT1
  sensor24: ivtULGT3_2
  sensor25: ivtULGT3_2
  sensor26: ivtULGT3_2
  sensor27: ivtLLGT3_3
  sensor28: ivtBVGT3_3
  sensor29: ivtSV3BVForskj
  sensor30: ivtEffektinkvitVVbehov
  sensor31: ivtTillskotstimerVVbehov
  sensor32: ivtTappvprio
  sensor33: ivtTillskotti10
  sensor34: ivtTillskottRAD
  sensor35: ivtTillskottTillagg
  sensor36: ivtDefaultSV2Open

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  ap:
    ssid: "Esphome-Web-209Bc6"
    password: "aNNBhu8OpME3"

captive_portal:

# Enable logging
logger:
  baud_rate: 0
